$(document).ready(function(){
	$("#gambar").mouseenter(function(){
		$("#kotak").hide()
	});
	$("#gambar").mouseleave(function(){
		$("#kotak").show({
		});
	});
	$("#gambar2").mouseenter(function(){
		$("#kotak2").hide()
	});
	$("#gambar2").mouseleave(function(){
		$("#kotak2").show()
	});
	$("#gambar3").mouseenter(function(){
		$("#kotak3").hide()
	});
	$("#gambar3").mouseleave(function(){
		$("#kotak3").show()
	});
	$("#gmbr").mouseenter(function(){
		$("#kotak4").hide()
	});
	$("#gmbr").mouseleave(function(){
		$("#kotak4").show()
	});
	$("#gmbr1").mouseenter(function(){
		$("#kotak5").hide()
	});
	$("#gmbr1").mouseleave(function(){
		$("#kotak5").show()
	});
	$("#gambar").mouseenter(function(){
		$("#tombol").show()
	});
	$("#gambar").mouseleave(function(){
		$("#tombol").hide()
	});
	$("#gambar2").mouseenter(function(){
		$("#tombol2").show()
	});
	$("#gambar2").mouseleave(function(){
		$("#tombol2").hide()
	});
	$("#gambar3").mouseenter(function(){
		$("#tombol3").show()
	});
	$("#gambar3").mouseleave(function(){
		$("#tombol3").hide()
	});
	$("#gmbr").mouseenter(function(){
		$("#tombol4").show()
	});
	$("#gmbr").mouseleave(function(){
		$("#tombol4").hide()
	});
	$("#gmbr1").mouseenter(function(){
		$("#tombol5").show()
	});
	$("#gmbr1").mouseleave(function(){
		$("#tombol5").hide()
	});
});